version: "3.9"

services:
  app:
    tty: true 
    restart: always
    image: ropify-app
    container_name: ropify-app
    build: .
    ports:
      - 8080:8080
    env_file:
      - .env
    networks:
      - application
    depends_on:
      db:
        condition: service_healthy
      background-removal-service:
        condition: service_started
    volumes:
      - .:/src/app
    command: air -c .air.toml
  
  db:
    image: postgres:alpine
    container_name: ropify-app-db
    environment:
      - POSTGRES_HOST=${DB_HOST}
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    ports:
      - 5432:5432
    volumes:
      - postgres-db:/var/lib/postgresql/data
    networks:
      - application
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER}"]
      interval: 10s
      timeout: 5s
      retries: 5
      
  background-removal-service:
    build: 
      context: ./background-removal-service
      dockerfile: Dockerfile
    container_name: background-removal-service
    ports:
      - 8000:8000
    networks:
      - application
    restart: always
    volumes:
      - ./background-removal-service:/app

networks:
  application:

volumes:
  postgres-db: